#para documentos do docker composer inicia-se com a versão do arquivo.
version: "3"
services:

  #banco de dados
  mysql:
    image: mysql:5.7
    container_name: nataldev-mysql
    environment:
      MYSQL_DATABASE: nataldev
      MYSQL_ROOT_PASSWORD: "senha"
    ports:
      - "3307:3306"
    volumes:
      - .docker/db:/var/lib/mysql
    restart: always


  # servidor web + php7.2 + laravel 5.6 (DEV)
  web-dev:
    build: .
    container_name: nataldev-dev-php
    ports:
      - "8888:80"
    volumes:
      - .docker/jenkins_home/workspaces/dev:/var/www/html
    depends_on:
      - mysql


  # servidor web + php7.2 + laravel 5.6 (HOMOLOGAÇÃO)
  web-hom:
    build: .
    container_name: nataldev-hom-php
    ports:
      - "8888:80"
    volumes:
      - .docker/jenkins_home/workspaces/hom:/var/www/html
    depends_on:
      - mysql


  # servidor web + php7.2 + laravel 5.6 (PRODUÇÃO)
  web-pro:
    build: .
    container_name: nataldev-pro-php
    ports:
      - "7777:80"
    volumes:
      - .docker/jenkins_home/workspaces/pro:/var/www/html
    depends_on:
      - mysql


  #jenkin servidor de automação
  jenkins:
    build: ./jenkins
    container_name: nataldev-jenkins
    ports:
      - "6666:8080"
      - "443:8443"
    volumes:
      - .docker/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    restart: always
